name: Configure AWS Credentials OIDC
description: Configure AWS Credentials OIDC

inputs:
  account:
    required: true
    type: string
  region:
    required: true
    type: string
  role_name:
    required: false
    type: string
    default: github-actions

runs:
  using: composite
  steps:
  - shell: bash
    run: |
      echo hello 1
      echo hello 2
