name: Docker Build & Push

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      build_path:
        required: false
        type: string
        default: .
      region:
        required: true
        type: string
      image_name:
        required: true
        type: string
      role_name:
        required: false
        type: string
        default: github-actions

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout joynbio/github-actions-workflows
      uses: actions/checkout@v2
      with:
        repository: joynbio/github-actions-workflows
        ref: main
        path: github-actions-workflows
    - name: Configure AWS Credentials OIDC
      run: github-actions-workflows/scripts/configure-aws-credentials-oidc.sh "${{inputs.account}}" "${{inputs.region}}" "${{inputs.role_name}}"
    - name: Build and Push
      run: |
        short_hash=$(git rev-parse --short HEAD | cut -c-7)
        echo "short_hash=$short_hash"
        docker login -u AWS -p "$(aws ecr get-login-password --region ${{ inputs.region }})" ${{ inputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com
        docker build ${{ inputs.build_path }} \
          -t "${{ inputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.image_name }}:latest" \
          -t "${{ inputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.image_name }}:$short_hash"
        docker push "${{ inputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.image_name }}:latest"
        docker push "${{ inputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.image_name }}:$short_hash"
